version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - aws s3 rm s3://home.sbroadhurst.net --recursive
      - aws s3 cp build s3://home.sbroadhurst.net --recursive --acl public-read

artifacts:
  files:
    build/**/*
  